#!/usr/bin/env sh
source "$HOME/.profile"

#      ALIASES
#================================
alias \
    ka="killall" \
	mkdir="mkdir -pv" \
	mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)" \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	yt="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \
	yta="yt -x -f bestaudio/best" \
	cp="cp --reflink=auto"

# keystroke Savers
alias \
    pacman="sudo pacman" \
    dnf="sudo dnf" \
    apt="sudo apt" \
    firewall='sudo firewall-cmd' \
    fw='firewall'

alias word='shuf -n1 /usr/share/dict/words'
alias dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
_dotfiles () {_git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME} #! Prep for moving into a script
alias mtr='mtr -n -o "LSRDNBAW"'


#      FUNCTIONS
#================================

mcd() {mkdir -pv $1; cd $1 ;}

# ---[ Consolecable functions ]--------------------------------------------- #

cisco-tty() {
  if [[ -z $1 ]]; then
    sudo screen /dev/ttyUSB0 9600
  else
    sudo screen /dev/ttyUSB${1} 9600
  fi
}

unifi-tty() {sudo screen /dev/ttyUSB0 115200}

# ---[ Loginctl ]----------------------------------------------------------- #

lock() {
  loginctl lock-session 1
  xset -display :0 dpms force off
}

unlock() {
  loginctl unlock-session 1
  xset -display :0 dpms force on
}

# ---[ Replace cat(1) with bat if available]-------------------------------- #

if command -v bat > /dev/null; then

  alias cat='bat -Pp'
  export MANPAGER="sh -c 'col -bx | bat -l man -p'"  

  batdiff() {
      git diff &>/dev/null
      if [[ "$?" == "0" ]] && [[ -z "$1" ]]; then
        # Pass the output of git diff to bat
        git diff --name-only --diff-filter=d | xargs bat --diff
      else
        # pass the output of diff to bat
        diff -u "$1" "$2" | bat -p
      fi
  }
fi
