# A minimal left prompt
format = """${custom.system_icons}$username$hostname$directory$shlvl$character"""

# move the rest of the prompt to the right
right_format = """$all$status"""

add_newline = false

[username]
format = "[$user]($style)@"

[cmd_duration]
format = '\[[⏱ $duration ]($style)\]'

[character]
success_symbol = "❯"
error_symbol = "❯"

[aws]
symbol = "  "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " "
truncation_symbol = "…/"
truncation_length = 5
#home_symbol = "ﴤ"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = "❯"
format = "[$symbol]($style)"
repeat = true
disabled = false

[swift]
symbol = "ﯣ "

[custom.ansible]
description = "Ansible version"
command = "echo -n $(ansible --version 2>/dev/null | grep ^ansible | awk '{ print $2 }') $(which ansible | sed -e s@$HOME/@@ -e s@/bin/ansible@@ -e s@/.virtual_env@@)"
when = """ test -n "${ANSIBLE_HOME}" """
files = [ "ansible.cfg" ]
shell = "/bin/bash"
symbol = "Ⓐ "
format = "[$symbol$output]($style) "

[custom.system_icons]
description = "Show system icons"
command     = '([ $(uname -s) == "Darwin" ] && echo ) || ([ $(uname -s) == "Linux" ] && echo )'
format      = "[$output]($style) "
style       = "bold"
shell       = ["bash", "--noprofile", "--norc"]
when        = "true"

[custom.git_email]
command = "git config user.email"
when = "git rev-parse --git-dir 2> /dev/null"
format = "by [$output]($style) "
style = "bright-yellow bold"
