add_newline = false
scan_timeout = 10

format = """
╭─[](fg:#fff1cf bold)[ $username ](fg:#252525 bg:#fff1cf bold)[ ](fg:#fff1cf bg:#6f6565 bold)(fg:#fff1cf)\
$directory$git_branch$git_status$python[](fg:#252525 bg:#6f6565)\
$time[  ](fg:#c4c431 bg:#6f6565)[](fg:#6f6565) $character
╰─> 
"""

[line_break]
disabled = false

[fill]
symbol = " "
style = "fg:#252525 bg:#6f6565"

[username]
format = ""
show_always = true
disabled = false

[hostname]
format = "[$ssh_symbol$hostname]($style)"
ssh_symbol = " "
ssh_only = false

[character]
success_symbol = "[](bold cyan)"
error_symbol = "[](bold red)"

[battery]
full_symbol = ""
format = "[ $symbol$percentage ](fg:#fff1cf)"

[[battery.display]]
threshold = 100

[time]
format = '[\[$time\]](fg:#fff1cf bg:#6f6565)'
utc_time_offset = "-4"
time_format = "%T"
disabled = false
time_range = "-"

[git_branch]
format = "[$symbol$branch ](bg:#252525)"
symbol = " "

[git_status]
format = '([\[$all_status$ahead_behind\] ](fg:#6f6565 bg:#252525))'

[directory]
format = "[$path ]($style)[$read_only](fg:#fff bg:#6f6565)[ ](fg:#6f6565 bg:#252525 bold)"
style = "fg:#fff1cf bg:#6f6565"
truncation_symbol = "…/"
truncate_to_repo = false
truncation_length = 100
home_symbol = "  "

[python]
symbol = "[](fg:#deb565 bg:#252525) "
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
style = "bg:#252525 fg:#6f6565"
